"""Add model_configs and system_prompt_templates tables"""

revision = '151579317f53'
down_revision = '202511151200'
branch_labels = None
depends_on = None

from alembic import op
import sqlalchemy as sa


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('model_configs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('model_name', sa.String(length=255), nullable=False),
    sa.Column('display_name', sa.String(length=255), nullable=False),
    sa.Column('thinking_behavior', sa.String(length=32), nullable=False),
    sa.Column('thinking_tags', sa.String(length=64), nullable=True),
    sa.Column('default_temperature', sa.Float(), nullable=False),
    sa.Column('default_max_tokens', sa.Integer(), nullable=False),
    sa.Column('max_context_tokens', sa.Integer(), nullable=False),
    sa.Column('supports_system_prompt', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_model_configs_model_name'), 'model_configs', ['model_name'], unique=True)
    op.create_table('system_prompt_templates',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('is_default', sa.Boolean(), nullable=False),
    sa.Column('category', sa.String(length=64), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('system_prompt_templates')
    op.drop_index(op.f('ix_model_configs_model_name'), table_name='model_configs')
    op.drop_table('model_configs')
    # ### end Alembic commands ###
